// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTqmGUtljuPpKfJYiyaJBrrpMHrIejGs',
    appId: '1:431081463760:web:967004c0a3bfe38d7e63d5',
    messagingSenderId: '431081463760',
    projectId: 'personoo',
    authDomain: 'personoo.firebaseapp.com',
    storageBucket: 'personoo.appspot.com',
    measurementId: 'G-5KH84VQB4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyKK5q5mnd-J-n-2iBOLvHTQ1-GLPgi10',
    appId: '1:431081463760:android:d00cedb29c3989707e63d5',
    messagingSenderId: '431081463760',
    projectId: 'personoo',
    storageBucket: 'personoo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIE9CmQpXdnNmiaHh8ThDLZTEL8HcMIjE',
    appId: '1:431081463760:ios:76621623191fcd307e63d5',
    messagingSenderId: '431081463760',
    projectId: 'personoo',
    storageBucket: 'personoo.appspot.com',
    iosClientId: '431081463760-679a1949tn2t0i29akgemtm2s5nb8ct6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mckenziechurchProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIE9CmQpXdnNmiaHh8ThDLZTEL8HcMIjE',
    appId: '1:431081463760:ios:76621623191fcd307e63d5',
    messagingSenderId: '431081463760',
    projectId: 'personoo',
    storageBucket: 'personoo.appspot.com',
    iosClientId: '431081463760-679a1949tn2t0i29akgemtm2s5nb8ct6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mckenziechurchProject1',
  );
}
